Name: Sync to Hugging Face Hub

on:
  push:
    branches: [main] # यदि आपकी मुख्य ब्रांच master है, तो यहाँ master लिखें

  # इसे आप manual भी चला सकते हैं
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://codebylogic:$HF_TOKEN@huggingface.co/spaces/codebylogic/my-ai-chatbot main
        
